version: '3'
services:
  db:    
    image: postgres:13-alpine
    container_name: postgres
    volumes:
       - postgres_volume:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_USER=rubyapp
      - POSTGRES_PASSWORD=rubyapp
      - POSTGRES_DB=rubyapp
    networks:
      - abd_network
    ports:
      - 5432:5432  
    image: postgres   
       
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      
    environment:
      - DB_USER=rubyapp
      - DB_NAME=rubyapp
      - DB_PASSWORD=rubyapp
      - DB_HOST=postgres
    networks:
      - abd_network   
      
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: on-failure   
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - db
    networks:
      - abd_network
    ports:
      - 8081:80

networks:
  abd_network:
    driver: bridge

volumes:
  postgres_volume:
    external: true